name: "SomfyCameraStream"
version: "1.0"
slug: "SomfyCameraStream"
description: "Un module permettant d'afficher un flux RTMPS dans Home Assistant."
url: "https://github.com/zarzak12/SomfyCameraStream"
startup: "services"
boot: "auto"
arch:
  - amd64
  - armv7
  - aarch64
ports:
  8080/tcp: 8080
options:
  rtmps_url: "rtmps://stream"
schema:
  rtmps_url: "str"
