name: "Somfy Outdoor"
description: "Conversion d'un flux RTMPS en HLS"
version: "1.0.0"
slug: "somfy-rtmps-to-hls"
init: false
webui: "http://[HOST]:8080/hls/index.m3u8"
ports:
  "7080/tcp": 7080
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  rtmps_url_input: "rtmps://ip-10-21-1-178.myfox.io/live/livecamera-YjU5MGZkNGY1YWVkNmRkYzEwMzJiOGY5OGI4ODE2MjUzMzM1YWM4NjczMzjQyMDQwMmExNzUyZGI1Nwx3ZS7P0wwUFjOZ2gXtFyqdUWO8u3LkHK"
  rtmps_url_output: "rtmp://localhost:1935/live/stream"
schema:
  rtmps_url_input: "str"
  rtmps_url_output: "str"