name: "Hello world"
description: "My first real add-on!"
version: "1.0.0"
slug: "hello_world"
init: false
host_network: true
ports:
  "8070/tcp": 8070
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  rtmps_url_input: "rtmps://stream"
  rtmps_url_output: "http://127.0.0.1:8070"
schema:
  rtmps_url_input: "str"
  rtmps_url_output: "str"