name: "Hello world"
description: "My first real add-on!"
version: "1.0.0"
slug: "hello_world"
init: false
ports:
  "7080/tcp": 7080
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  somfy_protect:
    username: mail@example.org
    password: P@ssw0rd
    sites:
      - Maison
  rtmps_url_input: "rtmps://ip-10-21-1-178.myfox.io/live/livecamera-YjU5MGZkNGY1YWVkNmRkYzEwMzJiOGY5OGI4ODE2MjUzMzM1YWM4NjczMzjQyMDQwMmExNzUyZGI1Nwx3ZS7P0wwUFjOZ2gXtFyqdUWO8u3LkHK"
  rtmps_url_output: "rtmp://localhost:1935/live/stream"
schema:
  somfy_protect:
    username: str
    password: str
    sites:
      - str
  rtmps_url_input: "str"
  rtmps_url_output: "str"