name: "Hello world"
description: "Somfy Protect plugin"
version: "1.0.0"
slug: "hello_world"
init: false
ports:
  "7081/tcp": 7081
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  somfy_protect:
    username: mail@example.org
    password: P@ssw0rd
    site: Maison
schema:
  somfy_protect:
    username: str
    password: str
    site: str