name: "Somfy Camera Streamer"
description: "Somfy Camera Streamer"
version: "1.0.0"
slug: "somfy_camera_streamer"
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  somfy_protect:
    username: mail@example.org
    password: "P@ssw0rd"
    site: Maison
  log_level: info
  seconds_between_quotes: 5
schema:
  somfy_protect:
    username: str
    password: password
    site: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
