# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SomfyCameraStream
version: "1.0.0"
slug: SomfyCameraStream
description: Un module permettant d'afficher un flux RTMPS dans Home Assistant.
url: "https://github.com/zarzak12/homeassistant-addons/tree/main/SomfyCameraStream"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - config:rw
options:
  somfy_protect:
    username: mail@example.org
    password: P@ssw0rd
    site: Maison
schema:
  somfy_protect:
    username: str
    password: str
    site: str
ports:
  "7080/tcp": 7080
