---
name: Somfy Camera Streamer
version: dev
slug: somfy_camera_streamer
description: Somfy Camera Streamer
url: https://github.com/zarzak12/SomfyCameraStream
codenotary: zarzak
init: false
arch:
  - aarch64
  - amd64
  - armv7
options:
  log_level: info
  seconds_between_quotes: 5
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_between_quotes: int(1,120)
